api_platform:
    title: Sentinel-Kit Server API
    version: 1.0.0
    formats:
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
