apiVersion: 1

datasources:
  - name: Elasticsearch-logs-es01
    type: elasticsearch
    url: http://sentinel-kit-db-elasticsearch-es01:9200
    access: proxy
    isDefault: false
    version: 9
    database: '*'
    jsonData:
      esVersion: 90
      timeField: '@timestamp'
      maxConcurrentShardRequests: 5
    readOnly: false
    orgId: 1
  - name: Elasticsearch-logs-es02
    type: elasticsearch
    url: http://sentinel-kit-db-elasticsearch-es02:9200
    access: proxy
    isDefault: false
    version: 9
    database: '*'
    jsonData:
      esVersion: 90
      timeField: '@timestamp'
      maxConcurrentShardRequests: 5
    readOnly: false
    orgId: 1