apiVersion: 1

datasources:
  - name: Elasticsearch-logs
    type: elasticsearch
    url: http://sentinel-kit-elasticsearch-db:9200
    access: proxy
    isDefault: false
    version: 9
    database: '*'
    jsonData:
      esVersion: 90
      timeField: '@timestamp'
      maxConcurrentShardRequests: 5
    readOnly: false
    orgId: 1