rules_folder: /app/elastalert_ruleset
run_every:
  seconds: 30
buffer_time:
  minutes: 15
es_host: sentinel-kit-db-elasticsearch-es01
es_port: 9200
es_username: elastic
use_ssl: true
verify_certs: true
ca_certs: /app/certs/ca/ca.crt
writeback_index: elastalert_status
alert_time_limit:
  days: 2
prometheus_port: 9091
prometheus_host: 0.0.0.0
es_conn_timeout: 60
max_query_size: 10000
max_aggregation: 1000
scroll_keepalive: 1m
